version: 2.2.0-build{build}
image: Visual Studio 2017
init:
- ps: >-
    if ($env:appveyor_repo_tag_name)
    {
      Update-AppveyorBuild -Version "$env:appveyor_repo_tag_name"
    }
before_build:
- cmd: dotnet restore src\LazyEntityGraph.sln
dotnet_csproj:
  patch: true
  assembly_version: "2.0.0.0"
  file_version: "2.2.0.{build}"
  informational_version: "{version}"
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
  - dotnet test .\src\LazyEntityGraph.Tests\LazyEntityGraph.Tests.csproj
  - dotnet test .\src\LazyEntityGraph.EntityFramework.Tests\LazyEntityGraph.EntityFramework.Tests.csproj
  - dotnet test .\src\LazyEntityGraph.EntityFrameworkCore.Tests\LazyEntityGraph.EntityFrameworkCore.Tests.csproj
deploy:
- provider: NuGet
  api_key:
    secure: "8x3Mcgshdo54GCog2ht9GKbVqGvXqrIiNO2KFlyvrS2Oe2F7OCDKoEbPIr8EjlWP"
  on:
    appveyor_repo_tag: true

